face-file-path: D:/graduate/face/
emoji-file-path: D:/graduate/emoji/
articlepics-path: D:/graduate/articlepics/
box-path: D:/graduate/box/
root-path: D:/graduate/

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    username: root
    password:  123456++q #admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduate_run?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    connect-timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  thymeleaf:
    cache: false
server:
  port: 9001



## 开启驼峰支持
#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
#  type-aliases-package: cn.wbnull.springbootdemo.model  #对应实体类路径
#  configuration:
#    map-underscore-to-camel-case: true

#mybatis:
##  type-aliases-package: org.larry.springboot.entity
#  mapper-locations: classpath:mapper/**/*.xml
#  check-config-location: true

